name: build

on:
  push:
    branches:
      - master
      - '**-devel'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - { ROS_DISTRO: foxy, ROS_REPO: ros }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: "ros-industrial/industrial_ci@master"
        env: ${{ matrix.env }}
